#!/bin/sh

# @version $Id: backup_info.sh 8 2017-06-26 10:07:43Z fixer $
# @date $Date: 2017-06-26 20:07:43 +1000 (Pn, 26 cze 2017) $
# @revision $Revision: 8 $
# @author $Author: fixer $
# @headurl $HeadURL: svn://.../repo_backup/backup_info.sh $

echo "======================" >> "$LOG_FILE"
echo "1. Info about NAS" >> "$LOG_FILE"
echo $(date +'%d-%m-%Y %H:%M:%S') >> "$LOG_FILE"
echo "======================" >> "$LOG_FILE"
echo "System: $(uname -a)" >> "$LOG_FILE" #albo cat /proc/version
echo "Host name: $(hostname)" >> "$LOG_FILE" #albo cat /proc/sys/kernel/hostname
echo "NAS version: $(cat /proc/sys/kernel/syno_hw_version)" >> "$LOG_FILE" #albo cat /proc/sys/kernel/hostname
echo "Serial number: $(cat /proc/sys/kernel/syno_serial)" >> "$LOG_FILE" #albo cat /proc/sys/kernel/hostname
echo "MAC ethernet adapter address 1: $(cat /proc/sys/kernel/syno_mac_address1)" >> "$LOG_FILE" #albo cat /proc/sys/kernel/hostname
echo "MAC ethernet adapter address 2: $(cat /proc/sys/kernel/syno_mac_address2)" >> "$LOG_FILE" #albo cat /proc/sys/kernel/hostname
echo "MAC ethernet adapter address 3: $(cat /proc/sys/kernel/syno_mac_address3)" >> "$LOG_FILE" #albo cat /proc/sys/kernel/hostname
echo "MAC ethernet adapter address 4: $(cat /proc/sys/kernel/syno_mac_address4)" >> "$LOG_FILE" #albo cat /proc/sys/kernel/hostname
# echo "NAS IP:`/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`"
echo " ----------- " >> "$LOG_FILE"
echo "Ethernet 1:" >> "$LOG_FILE"
/sbin/ifconfig eth0 >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Ethernet 2:" >> "$LOG_FILE"
/sbin/ifconfig eth1 >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Ethernet 3:" >> "$LOG_FILE"
/sbin/ifconfig eth2 >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Ethernet 4:" >> "$LOG_FILE"
/sbin/ifconfig eth3 >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Mem Info:" >> "$LOG_FILE"
echo "$(cat /proc/meminfo)" >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "CPU Info:" >> "$LOG_FILE"
echo "$(cat /proc/cpuinfo)" >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "mdstat info:" >> "$LOG_FILE"
echo "$(cat /proc/mdstat)" >> "$LOG_FILE" #informacje o RAID'zie
echo " ----------- " >> "$LOG_FILE"
echo "mdadm info:" >> "$LOG_FILE"
echo "for: md0" >> "$LOG_FILE"
mdadm --detail /dev/md0 >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "for: md1" >> "$LOG_FILE"
mdadm --detail /dev/md1 >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "for: md2" >> "$LOG_FILE"
mdadm --detail /dev/md2 >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "for: md3" >> "$LOG_FILE"
mdadm --detail /dev/md3 >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "for: md4" >> "$LOG_FILE"
mdadm --detail /dev/md4 >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "for: md5" >> "$LOG_FILE"
mdadm --detail /dev/md5 >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "diskstats info:" >> "$LOG_FILE"
echo "$(cat /proc/diskstats)" >> "$LOG_FILE" #fizyczne i logiczne dyski/partycje w systemie dla synków wielodyskowych
echo " ----------- " >> "$LOG_FILE"
echo "partitions info:" >> "$LOG_FILE"
echo "$(cat /proc/partitions)" >> "$LOG_FILE" #fizyczne i logiczne dyski/partycje w systemie (wszystkie modele)
echo " ----------- " >> "$LOG_FILE"
echo "fdisk info 1:" >> "$LOG_FILE"
echo "$(fdisk -l)" >> "$LOG_FILE" #też informacje o dysku
echo " ----------- " >> "$LOG_FILE"
echo "fdisk info 2:" >> "$LOG_FILE"
echo "$(fdisk -l -u)" >> "$LOG_FILE" #też informacje o dysku
echo " ----------- " >> "$LOG_FILE"
echo "pvdisplay info" >> "$LOG_FILE"
pvdisplay >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Display drive identification SDA:" >> "$LOG_FILE"
hdparm -i /dev/sda >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Display drive identification SDB:" >> "$LOG_FILE"
hdparm -i /dev/sdb >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Display drive identification SDC:" >> "$LOG_FILE"
hdparm -i /dev/sdc >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Display drive identification SDD:" >> "$LOG_FILE"
hdparm -i /dev/sdd >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Display drive identification SDE:" >> "$LOG_FILE"
hdparm -i /dev/sde >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Detailed/current information directly from drive SDA:" >> "$LOG_FILE"
hdparm -I /dev/sda >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Detailed/current information directly from drive SDB:" >> "$LOG_FILE"
hdparm -I /dev/sdb >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Detailed/current information directly from drive SDC:" >> "$LOG_FILE"
hdparm -I /dev/sdc >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Detailed/current information directly from drive SDD:" >> "$LOG_FILE"
hdparm -I /dev/sdd >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Detailed/current information directly from drive SDE:" >> "$LOG_FILE"
hdparm -I /dev/sde >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Display drive geometry SDA:" >> "$LOG_FILE"
hdparm -g /dev/sda >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Display drive geometry SDB:" >> "$LOG_FILE"
hdparm -g /dev/sdb >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Display drive geometry SDC:" >> "$LOG_FILE"
hdparm -g /dev/sdc >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Display drive geometry SDD:" >> "$LOG_FILE"
hdparm -g /dev/sdd >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "Display drive geometry SDE:" >> "$LOG_FILE"
hdparm -g /dev/sde >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "S.M.A.R.T. SDA:" >> "$LOG_FILE"
smartctl -a -d ata /dev/sda >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "S.M.A.R.T. SDB:" >> "$LOG_FILE"
smartctl -a -d ata /dev/sdb >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "S.M.A.R.T. SDC:" >> "$LOG_FILE"
smartctl -a -d ata /dev/sdc >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "S.M.A.R.T. SDD:" >> "$LOG_FILE"
smartctl -a -d ata /dev/sdd >> "$LOG_FILE"
echo " ----------- " >> "$LOG_FILE"
echo "S.M.A.R.T. SDE:" >> "$LOG_FILE"
smartctl -a -d ata /dev/sde >> "$LOG_FILE"
echo " " >> "$LOG_FILE"
echo " " >> "$LOG_FILE"